#
#  _____ _                    _____
# / ____| |                  / ____|   /\
#| (___ | |_ _ __ __ _ _   _| |       /  \
# \___ \| __| '__/ _` | | | | |      / /\ \
# ____) | |_| | | (_| | |_| | |____ / ____ \
#|_____/ \__|_|  \__,_|\__, |\_____/_/    \_\
#                       __/ |
#                      |___/
#

# CA Hub location coordinates in World and 'X Y Z Yaw Pitch' format.
CAHub_World: "world"
CAHub_Location:
  - 4944.5
  - 77.0
  - 4957.5

# CoolArena location coordinates in World and 'X Y Z Yaw Pitch' format.
CoolArena_World: "world"
CoolArena_Location:
  - -467.5
  - 142.0
  - 496.5

# Media Arena location coordinates in World and 'X Y Z Yaw Pitch' format.
MediaArena_World: "world"
MediaArena_Location:
  - -138.5
  - 40.0
  - -29.5

# How long, in seconds, before requests expire.
ExpiryTime: 60

# Messages:
Prefix: "&b&lStray &8> "
NoPermission: "&cYou do not have permission for this."
Sending: "&7Sending to CoolArena..."
NoPending: "&cYou do not have any pending requests."
Expired: "&cTeleport request expired."
ReqSent: "&7Teleport request sent!"
ClickReq: "&f[ &b游디 PLAYER sent you a CoolArena request, click here to accept! &f]"
ReqSentBeast: "&7Teleport request sent with Beast kit!"
ClickReqBeast: "&f[ &b游디 PLAYER sent you a CoolArena request with &lBeast Kit&r&b, click here to accept! &f]"
ReqSentSpeed: "&7Teleport request sent with Speed kit!"
ClickReqSpeed: "&f[ &b游디 PLAYER sent you a CoolArena request with &lSpeed Kit&r&b, click here to accept! &f]"
ReqSentAxe: "&7Teleport request sent with Axe kit!"
ClickReqAxe: "&f[ &b游디 PLAYER sent you a CoolArena request with &lAxe Kit&r&b, click here to accept! &f]"

# Do not use colour codes for ClickReqHover, they will not render correctly in-game.
ClickReqHover: "Click to teleport!"

NoUser: "&cCouldn't find a player with this username."
RequestExists: "&cThis player already has a pending request."

# Media Arena
SendingMedia: "&7Sending you to Media Arena..."
ClickReqMedia: "&f[ &c游디 PLAYER sent you a Media Arena request, click here to accept! &f]"